"""Build a test external gear pump as a STEP file with known geometry.

The gears are cut by a simulated standard rack (ISO 53 profile: addendum 1 m,
dedendum 1.25 m, sharp cutter tip), so the flanks are true involutes with a
trochoid root fillet, exactly as a hobbed gear. Each flank is written as a
B-spline, tips and roots as circular arcs, and the housing bore as two true
cylinders, so the STEP file looks like one made in a CAD system.

A JSON file with the design values (the truth used to check the app) is
written next to the STEP file.

    python tools/make_test_pump.py --name pump_A --z1 12 --z2 12 --m 3 \
        --alpha 20 --x1 0.2 --x2 0.2 --b 20 --hr 0.02 --backlash 0.05
"""

import argparse
import json
from pathlib import Path

import numpy as np
from shapely import affinity
from shapely.geometry import Point, Polygon
from shapely.ops import unary_union

import cadquery as cq


def inv(phi):
    return np.tan(phi) - phi


def inv_inverse(y):
    phi = np.cbrt(3.0 * y) if y > 0 else 0.0
    for _ in range(60):
        step = (np.tan(phi) - phi - y) / np.tan(phi) ** 2
        phi -= step
        if abs(step) < 1e-15:
            break
    return phi


def tooth_flank(z, m, alpha_deg, x, steps=2500):
    """Upper flank of tooth 0 (tooth centred on +x), from root to tip.

    Returns (r, theta) arrays: polar radius and angle measured from the
    tooth centre line. The tooth space is generated by rolling a rack
    cutter tooth past the gear blank.
    """
    al = np.radians(alpha_deg)
    r = m * z / 2
    ra = r + (1 + x) * m
    rf = r + x * m - 1.25 * m
    t = np.tan(al)
    w = np.pi * m / 4                       # half cutter tooth at the reference line
    hb, hc = 1.0 * m, 1.25 * m
    # cutter tooth pointing to the gear centre, reference line at y = 0
    cut = Polygon([(-w - hb * t, hb), (-w + hc * t, -hc), (w - hc * t, -hc),
                   (w + hb * t, hb), (w + hb * t, 4 * m), (-w - hb * t, 4 * m)])
    cut = affinity.translate(cut, 0, r + x * m)
    span = 2.2 * (ra * ra - (r * np.cos(al)) ** 2) ** 0.5 / r + 4 * np.pi / z
    pos = []
    for phi in np.linspace(-span, span, steps):
        c = affinity.translate(cut, -r * phi, 0)
        pos.append(affinity.rotate(c, -phi, origin=(0, 0), use_radians=True))
    space = unary_union(pos)                # space centred on +y (90 deg)
    gear = Point(0, 0).buffer(ra, 4096).difference(space)
    xy = np.asarray(gear.exterior.coords)
    rr = np.hypot(xy[:, 0], xy[:, 1])
    th = np.arctan2(xy[:, 1], xy[:, 0]) - np.pi / 2       # from space centre
    # one side of the space (theta < 0) is the upper flank of the tooth below
    sel = (th < 0) & (th > -np.pi / z) & (rr > rf + 2e-4) & (rr < ra - 2e-4)
    rr, th = rr[sel], th[sel]
    o = np.argsort(rr)
    rr, th = rr[o], th[o]
    th_tooth = np.pi / z + th               # tooth centred on 0, flank above it
    # area of one tooth space inside the tip circle (exact rack-cut shape)
    a_space = Point(0, 0).buffer(ra, 4096).intersection(space).area
    return rr, th_tooth, ra, rf, a_space


def _resample(rr, th, n):
    """Pick n points spread along the flank's arc length."""
    xy = np.column_stack([rr * np.cos(th), rr * np.sin(th)])
    s = np.concatenate([[0], np.cumsum(np.hypot(*np.diff(xy, axis=0).T))])
    keep = np.searchsorted(s, np.linspace(0, s[-1], n))
    keep = np.unique(np.clip(keep, 0, len(s) - 1))
    return rr[keep], th[keep]


def gear_wire(z, m, alpha_deg, x, centre=(0.0, 0.0), rot=0.0, npts=40):
    rr, th, ra, rf, a_space = tooth_flank(z, m, alpha_deg, x)
    rr, th = _resample(rr, th, npts)
    # pin the flank ends on the root and tip circles
    rr = rr.copy()
    rr[0], rr[-1] = rf, ra
    cx, cy = centre
    pitch = 2 * np.pi / z

    def V(r_, a_):
        return cq.Vector(cx + r_ * np.cos(a_ + rot), cy + r_ * np.sin(a_ + rot), 0)

    edges = []
    for k in range(z):
        a0 = k * pitch
        lower = [V(r_, a0 - t_) for r_, t_ in zip(rr, th)]          # root -> tip
        upper = [V(r_, a0 + t_) for r_, t_ in zip(rr[::-1], th[::-1])]   # tip -> root
        edges.append(cq.Edge.makeSpline(lower))
        edges.append(cq.Edge.makeThreePointArc(lower[-1], V(ra, a0), upper[0]))
        edges.append(cq.Edge.makeSpline(upper))
        nxt = V(rr[0], a0 + pitch - th[0])
        edges.append(cq.Edge.makeThreePointArc(upper[-1], V(rf, a0 + pitch / 2), nxt))
    return cq.Wire.assembleEdges(edges), ra, rf, a_space


def build(args):
    al = np.radians(args.alpha)
    z1, z2, m = args.z1, args.z2, args.m
    # zero-backlash centre distance, then open it up for the wanted backlash
    inv_aw0 = 2 * np.tan(al) * (args.x1 + args.x2) / (z1 + z2) + inv(al)
    aw0 = inv_inverse(inv_aw0)
    a0 = m * (z1 + z2) / 2 * np.cos(al) / np.cos(aw0)

    rb1, rb2 = m * z1 / 2 * np.cos(al), m * z2 / 2 * np.cos(al)

    def backlash(a):
        aw = np.arccos((rb1 + rb2) / a)
        rw1, rw2 = rb1 / np.cos(aw), rb2 / np.cos(aw)
        s1 = m * (np.pi / 2 + 2 * args.x1 * np.tan(al))
        s2 = m * (np.pi / 2 + 2 * args.x2 * np.tan(al))
        sw1 = rw1 * (s1 / (m * z1 / 2) + 2 * (inv(al) - inv(aw)))
        sw2 = rw2 * (s2 / (m * z2 / 2) + 2 * (inv(al) - inv(aw)))
        return 2 * np.pi * rw1 / z1 - sw1 - sw2, aw, rw1, rw2

    lo, hi = a0, a0 + 1.0
    for _ in range(100):
        mid = 0.5 * (lo + hi)
        if backlash(mid)[0] < args.backlash:
            lo = mid
        else:
            hi = mid
    a = 0.5 * (lo + hi)
    j, aw, rw1, rw2 = backlash(a)

    # tooth 0 of gear 1 on +x would hit gear 2; turn gear 2 so a space faces gear 1
    w1, ra1, rf1, as1 = gear_wire(z1, m, args.alpha, args.x1, (0, 0), rot=np.radians(args.rot1))
    w2, ra2, rf2, as2 = gear_wire(z2, m, args.alpha, args.x2, (a, 0),
                             rot=np.pi + np.pi / z2 - np.radians(args.rot1) * z1 / z2)
    b = args.b
    bore1, bore2 = 0.35 * rf1, 0.35 * rf2

    def gear_solid(w, cx, rbore):
        hole = cq.Wire.makeCircle(rbore, cq.Vector(cx, 0, 0), cq.Vector(0, 0, 1))
        face = cq.Face.makeFromWires(w, [hole])
        return cq.Solid.extrudeLinear(face, cq.Vector(0, 0, b))

    g1 = gear_solid(w1, 0.0, bore1)
    g2 = gear_solid(w2, a, bore2)

    # housing: block with a figure-eight bore and two drilled side ports at x = a/2
    hr = args.hr
    R1, R2 = ra1 + hr, ra2 + hr
    W = max(R1, R2) + 15
    g = args.cover_gap or 0.0
    zb, hb = -g, b + 2 * g               # body spans the gears plus the axial gaps
    blk = (cq.Workplane("XY").box(a + 2 * W, 2 * W, hb, centered=(False, False, False))
           .translate((-W, -W, zb)))
    blk = blk.cut(cq.Workplane("XY").workplane(offset=zb).circle(R1).extrude(hb))
    blk = blk.cut(cq.Workplane("XY").workplane(offset=zb).center(a, 0).circle(R2).extrude(hb))
    pw = args.port_width
    if pw >= b:
        raise ValueError("port diameter must be smaller than the face width")
    for sgn in (-1, 1):
        # drilled port: cylinder along y from the bore to the outside
        port = cq.Solid.makeCylinder(pw / 2, W + 1, cq.Vector(a / 2, 0, b / 2),
                                     cq.Vector(0, sgn, 0))
        blk = blk.cut(cq.Workplane("XY").add(port))
    parts = [g1, g2, blk.val()]
    if args.cover_gap is not None:
        # end covers (side plates) seated on the body, leaving the axial gap
        T = 8.0
        for z0 in (zb - T, zb + hb):
            cov = (cq.Workplane("XY").box(a + 2 * W, 2 * W, T, centered=(False, False, False))
                   .translate((-W, -W, z0)))
            parts.append(cov.val())

    comp = cq.Compound.makeCompound(parts)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    step = out / f"{args.name}.step"
    cq.exporters.export(comp, str(step))

    truth = {
        "name": args.name, "units": "mm",
        "drive_gear": {"z": z1, "x": args.x1, "ra": ra1, "rf": rf1, "rb": rb1,
                       "r_pitch": m * z1 / 2, "bore": bore1, "centre": [0, 0, 0],
                       "tooth_space_area": as1},
        "driven_gear": {"z": z2, "x": args.x2, "ra": ra2, "rf": rf2, "rb": rb2,
                        "r_pitch": m * z2 / 2, "bore": bore2, "centre": [a, 0, 0],
                        "tooth_space_area": as2},
        "module": m, "alpha_deg": args.alpha, "ha": 1.0, "hf": 1.25,
        "centre_distance": a, "alpha_w_deg": float(np.degrees(aw)),
        "rw1": rw1, "rw2": rw2, "backlash": j, "face_width": b,
        "tip_clearance": hr, "bore_radius_1": R1, "bore_radius_2": R2,
        "port_width": pw, "lateral_gap": args.cover_gap, "ports": "drilled holes of diameter port_width on the y axis through x = a/2, centred at mid face width",
        "axis": [0, 0, 1],
        "contact_ratio": float((np.sqrt(ra1 ** 2 - rb1 ** 2) + np.sqrt(ra2 ** 2 - rb2 ** 2)
                                - a * np.sin(aw)) / (np.pi * m * np.cos(al))),
    }
    (out / f"{args.name}.json").write_text(json.dumps(truth, indent=2))
    print(f"wrote {step} ({step.stat().st_size / 1e6:.2f} MB), a = {a:.5f} mm")
    return truth


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--name", default="pump")
    p.add_argument("--out-dir", default="test_pumps")
    p.add_argument("--z1", type=int, default=12)
    p.add_argument("--z2", type=int, default=12)
    p.add_argument("--m", type=float, default=3.0)
    p.add_argument("--alpha", type=float, default=20.0)
    p.add_argument("--x1", type=float, default=0.0)
    p.add_argument("--x2", type=float, default=0.0)
    p.add_argument("--b", type=float, default=20.0, help="face width, mm")
    p.add_argument("--hr", type=float, default=0.02, help="radial tip clearance, mm")
    p.add_argument("--backlash", type=float, default=0.05, help="circumferential, mm")
    p.add_argument("--port-width", type=float, default=8.0)
    p.add_argument("--cover-gap", type=float, default=None,
                   help="add end covers with this axial gap to the gear faces, mm")
    p.add_argument("--rot1", type=float, default=0.0, help="drive gear angle, deg")
    build(p.parse_args(argv))


if __name__ == "__main__":
    main()
